import numpy as np
arr1=np.arange(4,8).reshape((2,2))
print(arr1)
#1
b=np.power(arr1,3)
print(b)
c=np.multiply(arr1,arr1)
d=np.multiply(c,arr1)
print(d)
e=arr1*arr1*arr1
print(e)
f=arr1**3
print(f)
#2
h=np.identity(2)
print(h)
#3
i=np.power(arr1[0][0],2)
j=np.power(arr1[0][1],3)
k=np.power(arr1[1][0],4)
m=np.power(arr1[1][1],5)
print(i)
print(j)
print(k)
print(m)
#4
arr2=np.arange(0,4).reshape((2,2))
print(arr2)
n=np.power(arr1,2)
o=np.multiply(2,arr2)
print(o)
p=np.add(n,o)
print(p)